/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          blue: "#3B5BDB",
          "blue-light": "#4C6EF5",
          navy: "#1E3A8A",
          lime: "#A3D045",
          dark: "#0F1524",
          light: "#F8F9FE",
          lighter: "#EEF2FF",
          white: "#FFFFFF",
        },
        // Dark theme
        dark: {
          bg: "#0d1340",
          "bg-card": "#1a2160",
          "bg-card-hover": "#1e2870",
          "bg-hero": "#0d1340",
          nav: "#0d1340",
          text: "#ffffff",
          "text-muted": "rgba(255,255,255,0.65)",
          "text-subtle": "rgba(255,255,255,0.45)",
          accent: "#c8f135",
          "accent-text": "#0d1340",
          "btn-primary": "#c8f135",
          "btn-primary-text": "#0d1340",
          "btn-secondary": "transparent",
          "btn-secondary-text": "#ffffff",
          "tag-bg": "rgba(255,255,255,0.1)",
          "tag-text": "rgba(255,255,255,0.7)",
          "stat-card": "#1a2160",
          "terminal-bg": "#0a0e1a",
          "footer-bg": "#070c2e",
          "footer-text": "rgba(255,255,255,0.5)",
          "member-bg": "#2a3275",
        },
        // Light theme
        light: {
          bg: "#f4f5fa",
          "bg-card": "#ffffff",
          "bg-card-hover": "#f0f2ff",
          "bg-hero": "#f4f5fa",
          nav: "#ffffff",
          text: "#0d1340",
          "text-muted": "rgba(13,19,64,0.7)",
          "text-subtle": "rgba(13,19,64,0.45)",
          accent: "#0d1340",
          "accent-text": "#c8f135",
          "btn-primary": "#0d1340",
          "btn-primary-text": "#ffffff",
          "btn-secondary": "transparent",
          "btn-secondary-text": "#0d1340",
          "tag-bg": "rgba(13,19,64,0.08)",
          "tag-text": "rgba(13,19,64,0.65)",
          "stat-card": "#eef0fa",
          "terminal-bg": "#1a1a2e",
          "footer-bg": "#e8eaf5",
          "footer-text": "rgba(13,19,64,0.55)",
          "member-bg": "#e0e4f5",
        },
      },
      fontFamily: {
        sans: ["Onest", "system-ui", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        serif: ["DM Serif Display", "serif"],
      },
      fontWeight: {
        thin: "100",
        extralight: "200",
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
        black: "900",
      },
      animation: {
        cursor: "cursor 1s infinite",
      },
      keyframes: {
        cursor: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};